### ISSUE TITLE
Some packages point to the node_modules path

### ISSUE THREAD

**Issue by trevordunn** [wdamien/findl#5]
```
@react-navigation/bottom-tabs (MIT)
Bottom tab navigator following iOS design guidelines
https://github.com/react-navigation/react-navigation
node_modules/@react-navigation/bottom-tabs/LICENSE
```

If it can find it, I would expect this package to point to this url (or the raw url):
https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/LICENSE

Note: this might be related to #1.

**Comment by wdamien** [comment]
Fixed in https://github.com/wdamien/findl/commit/b07e4bbbf330cf3bdceb07a7d50f3586e0d066cc It should cover most repos. If any repos don't work with the latest version, please post them here.

**Comment by trevordunn** [comment]
Still happening for these npm packages: `html-minifier`, `react`
